"""Django settings for ludamus project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
from pathlib import Path

import environ
from google.oauth2 import service_account

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env(
    # Domains
    ALLOWED_HOSTS=(list, ["localhost"]),
    ROOT_DOMAIN=(str, ""),
    SESSION_COOKIE_DOMAIN=(str, None),
    VITE_PORT=(int, 5173),
    # Auth0
    AUTH0_CLIENT_ID=(str, ""),
    AUTH0_CLIENT_SECRET=(str, ""),
    AUTH0_DOMAIN=(str, ""),
    # Database
    DB_NAME=(str, ""),  # Database name or file path
    USE_POSTGRES=(bool, False),
    # Static files
    GIT_COMMIT_SHA=(str, "1"),
    MEDIA_ROOT=(str, str(BASE_DIR / "media")),
    STATIC_ROOT=(str, str(BASE_DIR / "staticfiles")),
    # Google Cloud Storage (media) — set all three to enable GCS
    GS_BUCKET_NAME=(str, ""),
    GS_CREDENTIALS_JSON=(str, ""),
    GS_LOCATION=(str, ""),
    # Membership API
    MEMBERSHIP_API_BASE_URL=(str, ""),
    MEMBERSHIP_API_CHECK_INTERVAL=(int, 15),
    MEMBERSHIP_API_TIMEOUT=(int, 30),
    MEMBERSHIP_API_TOKEN=(str, ""),
    # Other
    CREDENTIALS_ENCRYPTION_KEY=str,
    DEBUG=(bool, False),
    ENV=str,
    SECRET_KEY=str,
    SUPPORT_EMAIL=(str, "support@example.com"),
    IN_TESTS=(bool, False),
)


# Environment configuration
ENV = env("ENV")
IS_PRODUCTION = ENV == "production"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env("SECRET_KEY")

# Fernet key for encrypting import-connection credentials at rest.
# Distinct from SECRET_KEY so it can rotate independently. Url-safe
# base64-encoded 32 bytes (output of Fernet.generate_key()).
CREDENTIALS_ENCRYPTION_KEY = env("CREDENTIALS_ENCRYPTION_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# Parse comma-separated allowed hosts for production
ALLOWED_HOSTS: list[str] = env("ALLOWED_HOSTS")

# Append localhost and its subdomains for development
if ENV == "development":
    ALLOWED_HOSTS.extend([".localhost", ".local", "localhost", "127.0.0.1"])

SESSION_COOKIE_DOMAIN = env("SESSION_COOKIE_DOMAIN") or None

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.flatpages",
    # Third Party
    "django_extensions",
    "django_vite",
    "heroicons",
    # First Party
    "ludamus.adapters.web.django.apps.WebMainConfig",
    "ludamus.adapters.db.django.apps.DBMainConfig",
    "ludamus.gates.cli.django.apps.CliGatesConfig",
    "ludamus.gates.web.django.apps.WebGatesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "ludamus.inits.RepositoryInjectionMiddleware",
    "ludamus.inits.middleware.ServiceInjectionMiddleware",
    "ludamus.adapters.web.django.middlewares.RequestContextMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ludamus.adapters.web.django.middlewares.RedirectErrorMiddleware",
    "django.contrib.flatpages.middleware.FlatpageFallbackMiddleware",
]

if DEBUG:
    INSTALLED_APPS.append("django_browser_reload")
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

if DEBUG and env.bool("DEBUG_TOOLBAR", default=False):
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

ROOT_URLCONF = "ludamus.gates.web.django.urls"

_BASE_TEMPLATE_LOADERS = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

_TEMPLATE_LOADERS: list[str | tuple[str, list[str]]] = (
    [("django.template.loaders.cached.Loader", _BASE_TEMPLATE_LOADERS)]
    if IS_PRODUCTION
    else list(_BASE_TEMPLATE_LOADERS)
)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": False,
        "OPTIONS": {
            "loaders": _TEMPLATE_LOADERS,
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.media",
                "ludamus.gates.web.django.context_processors.sites",
                "ludamus.gates.web.django.context_processors.support",
                "ludamus.gates.web.django.context_processors.static_version",
                "ludamus.gates.web.django.context_processors.current_user",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "libraries": {
                "avatar_tags": "ludamus.gates.web.django.templatetags.avatar_tags"
            },
            "debug": DEBUG or env("IN_TESTS"),
            "string_if_invalid": "" if IS_PRODUCTION else "ERROR: Missing variable %s",
        },
    }
]

WSGI_APPLICATION = "ludamus.edges.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = (
    {
        "default": {
            "ATOMIC_REQUESTS": True,
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME"),
            "USER": env.str("DB_USER"),
            "PASSWORD": env.str("DB_PASSWORD"),
            "HOST": env.str("DB_HOST"),
            "PORT": env.str("DB_PORT"),
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {"connect_timeout": 10},
        }
    }
    if env("USE_POSTGRES")
    else {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": env("DB_NAME"),
            "OPTIONS": {
                "timeout": 20,
                "init_command": "PRAGMA journal_mode=WAL;",
                "transaction_mode": "IMMEDIATE",
            },
        }
    }
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        )
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pl"

LANGUAGES = [("pl", "Polski"), ("en", "English")]

TIME_ZONE = "Europe/Warsaw"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / "locale"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

# URL prefixes that skip middleware processing (UoW injection, context setup)
MIDDLEWARE_SKIP_PREFIXES = (
    STATIC_URL,
    "/admin/",
    "/__debug__/",
    "/__reload__/",
    "/healthz/",
    "/media/",
)

# Cache busting version for static files (set via GIT_COMMIT_SHA env var during build)
STATIC_VERSION = env("GIT_COMMIT_SHA")[:8]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Auth

AUTH_USER_MODEL = "db_main.User"
LOGIN_URL = "/crowd/login-required/"

# Sites

ROOT_DOMAIN = env("ROOT_DOMAIN")

# Auth0

AUTH0_CLIENT_ID = env("AUTH0_CLIENT_ID")
AUTH0_CLIENT_SECRET = env("AUTH0_CLIENT_SECRET")
AUTH0_DOMAIN = env("AUTH0_DOMAIN")

# Support

SUPPORT_EMAIL = env("SUPPORT_EMAIL")

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Security Settings for Production
if IS_PRODUCTION:
    # HTTPS/SSL Settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # HSTS Settings (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Session Security
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"  # Changed from Strict to allow OAuth callbacks
    SESSION_COOKIE_AGE = 3600 * 24 * 30  # 30 days
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False

    # CSRF Security
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = "Lax"  # Changed from Strict to allow OAuth callbacks
    CSRF_TRUSTED_ORIGINS = []
    for host in ALLOWED_HOSTS:
        if host.startswith("."):
            bare = host[1:]
            CSRF_TRUSTED_ORIGINS.extend([f"https://{bare}", f"https://*.{bare}"])
        else:
            CSRF_TRUSTED_ORIGINS.append(f"https://{host}")

    # Additional Security Settings
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

    SECURE_REDIRECT_EXEMPT = [r"^healthz/"]

    # File Upload Security
    FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
    DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
else:
    # Development settings
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = "Lax"


MEDIA_ROOT = env("MEDIA_ROOT")
MEDIA_URL = "/media/"

# Default storage — GCS when all three GS_ vars are set, filesystem otherwise.
# Independent of IS_PRODUCTION so GCS can be exercised locally.
GS_BUCKET_NAME = env("GS_BUCKET_NAME")
GS_CREDENTIALS_JSON = env("GS_CREDENTIALS_JSON")
GS_LOCATION = env("GS_LOCATION")

if GS_BUCKET_NAME and GS_CREDENTIALS_JSON and GS_LOCATION:
    gs_credentials = service_account.Credentials.from_service_account_info(  # type: ignore[no-untyped-call]
        json.loads(GS_CREDENTIALS_JSON)
    )
    default_storage_backend: dict[str, object] = {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        "OPTIONS": {
            "bucket_name": GS_BUCKET_NAME,
            "credentials": gs_credentials,
            "location": GS_LOCATION,
            "default_acl": None,
            "querystring_auth": False,
        },
    }
else:
    default_storage_backend = {"BACKEND": "django.core.files.storage.FileSystemStorage"}

if IS_PRODUCTION:
    STATIC_ROOT = env("STATIC_ROOT")
    STORAGES = {
        "default": default_storage_backend,
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
        },
    }
else:
    # Development email backend
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    STORAGES = {
        "default": default_storage_backend,
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        },
    }

# Cache configuration
CACHES = (
    {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "cache_table",
        }
    }
    if IS_PRODUCTION
    else {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} {message}",
            "style": "{",
        }
    },
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "verbose"}},
    "root": {"handlers": ["console"], "level": "INFO" if IS_PRODUCTION else "DEBUG"},
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING" if IS_PRODUCTION else "INFO",
            "propagate": False,
        },
    },
}

# Membership API Configuration
MEMBERSHIP_API_BASE_URL = env("MEMBERSHIP_API_BASE_URL")
MEMBERSHIP_API_TOKEN = env("MEMBERSHIP_API_TOKEN")
MEMBERSHIP_API_TIMEOUT = env("MEMBERSHIP_API_TIMEOUT")
MEMBERSHIP_API_CHECK_INTERVAL = env("MEMBERSHIP_API_CHECK_INTERVAL")

# Vendor Dependencies Configuration
# Download with: mise run dj downloadvendor
# SHA-384 hashes use base64 encoding (SRI format)
VENDOR_DEPENDENCIES: list[dict[str, str]] = [
    {
        "name": "popperjs",
        "url": (
            "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        ),
        "filename": "popper.min.js",
        "sha384": "oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3",
    },
    {
        "name": "popperjs-map",
        "url": (
            "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js.map"
        ),
        "filename": "popper.min.js.map",
        "sha384": "cGZ11hmqUooIlGMY+Y+gi+8AhjA4H/Qa29LQBPWKKzhmbsxvNpyWrPuBJCprTsil",
    },
    {
        "name": "htmx",
        "url": "https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js",
        "filename": "htmx.min.js",
        "sha384": "/TgkGk7p307TH7EXJDuUlgG3Ce1UVolAOFopFekQkkXihi5u/6OCvVKyz1W+idaz",
    },
]

VENDOR_STATIC_DIR = BASE_DIR / "static" / "vendor"

# Vite asset pipeline
DJANGO_VITE = {
    "default": {
        "dev_mode": ENV == "development" or ROOT_DOMAIN == "testserver",
        "dev_server_host": "localhost",
        "dev_server_port": env("VITE_PORT"),
        "static_url_prefix": "vite",
        "manifest_path": BASE_DIR / "static" / "vite" / "manifest.json",
    }
}
