# Generated by Django 5.2.7 on 2025-10-18 06:02

from django.db import migrations, models

import ludamus.pacts.crowd


class Migration(migrations.Migration):

    dependencies = [("db_main", "0024_delete_guild")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("active", "ACTIVE"),
                    ("connected", "CONNECTED"),
                    ("anonymous", "ANONYMOUS"),
                ],
                default=ludamus.pacts.crowd.UserType["ACTIVE"],
                max_length=255,
            ),
        )
    ]
