# Generated by Django 6.0.5 on 2026-05-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0078_alter_eventintegration_config_json")]

    operations = [
        migrations.RemoveConstraint(model_name="session", name="session_min_age_range"),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_age__gte", 0), ("min_age__lte", 80)),
                name="session_min_age_range",
            ),
        ),
    ]
