# Generated by Django 6.0.5 on 2026-06-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0081_event_logo")]

    operations = [
        migrations.AddField(
            model_name="sphere",
            name="logo",
            field=models.ImageField(blank=True, upload_to="spheres/"),
        )
    ]
