# Generated by Django 6.0.5 on 2026-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0081_eventintegration_questions_snapshot_json")]

    operations = [
        migrations.AddField(
            model_name="eventintegration",
            name="import_failures_json",
            field=models.TextField(default="[]"),
        )
    ]
