# Generated by Django 6.0.6 on 2026-06-14 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0083_proposalcategory_offer_claim_window_and_more")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shadowbanned",
            field=models.ManyToManyField(
                blank=True, related_name="shadowbanned_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("waitlist_promoted", "WAITLIST_PROMOTED"),
                    ("waitlist_offer", "WAITLIST_OFFER"),
                    ("offer_expired", "OFFER_EXPIRED"),
                    ("shadowbanned_signup", "SHADOWBANNED_SIGNUP"),
                ],
                max_length=32,
            ),
        ),
    ]
