# Generated by Django 6.0.6 on 2026-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0083_proposalcategory_offer_claim_window_and_more")]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="accreditation_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("standard", "Standard"),
                    ("guest", "Guest"),
                    ("honorary", "Honorary"),
                ],
                default="none",
                max_length=20,
            ),
        )
    ]
