# Generated by Django 6.0.6 on 2026-06-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0084_user_shadowbanned_alter_notification_kind")]

    # SQLite cannot ALTER an auto-created M2M into one backed by a custom
    # through model, so drop the plain M2M and recreate it through Shadowban.
    # The feature is unreleased, so there is no data to preserve.
    operations = [
        migrations.RemoveField(model_name="user", name="shadowbanned"),
        migrations.CreateModel(
            name="Shadowban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadowbans_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadowbans_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "shadowban"},
        ),
        migrations.AddField(
            model_name="user",
            name="shadowbanned",
            field=models.ManyToManyField(
                blank=True,
                related_name="shadowbanned_by",
                through="db_main.Shadowban",
                through_fields=("owner", "target"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="shadowban",
            constraint=models.UniqueConstraint(
                fields=("owner", "target"), name="shadowban_unique_owner_target"
            ),
        ),
    ]
