# Generated by Django 6.0.6 on 2026-06-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0081_event_session_cover_images"),
        ("db_main", "0084_remove_importlogentry_ile_int_row_idx_and_more"),
    ]

    operations = []
