# Generated by Django 6.0.6 on 2026-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0086_eventban")]

    operations = [
        migrations.AddConstraint(
            model_name="shadowban",
            constraint=models.CheckConstraint(
                condition=models.Q(("owner", models.F("target")), _negated=True),
                name="shadowban_owner_not_target",
            ),
        )
    ]
