# Generated by Django 6.0.6 on 2026-06-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0092_merge_import_and_main")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_sessions",
                to="db_main.event",
            ),
        )
    ]
