# Generated by Django 6.0.6 on 2026-06-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0098_drop_session_sphere")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="use_session_cover_placeholders",
            field=models.BooleanField(default=False),
        )
    ]
