# Generated by Django 6.0.6 on 2026-06-27 15:43

from django.db import migrations, models

import ludamus.pacts.legacy


class Migration(migrations.Migration):

    dependencies = [("db_main", "0101_space_event_required")]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("accepted", "ACCEPTED"),
                    ("on_hold", "ON_HOLD"),
                    ("rejected", "REJECTED"),
                    ("scheduled", "SCHEDULED"),
                ],
                default=ludamus.pacts.legacy.SessionStatus["PENDING"],
                max_length=15,
            ),
        )
    ]
