# Generated by Django 6.0.6 on 2026-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0111_remove_user_manager")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("waitlist_promoted", "WAITLIST_PROMOTED"),
                    ("waitlist_offer", "WAITLIST_OFFER"),
                    ("offer_expired", "OFFER_EXPIRED"),
                    ("shadowbanned_signup", "SHADOWBANNED_SIGNUP"),
                    ("party_invite", "PARTY_INVITE"),
                ],
                max_length=32,
            ),
        )
    ]
