# Generated by Django 6.0.6 on 2026-07-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0112_alter_notification_kind")]

    operations = [
        migrations.AddField(
            model_name="sessionparticipation",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_participations",
                to="db_main.party",
            ),
        )
    ]
