# Generated by Django 6.0.6 on 2026-07-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0107_facilitatorchangelog"),
        ("db_main", "0115_sessionparticipation_enrolled_by"),
    ]

    operations = []
