# Generated by Django 6.0.6 on 2026-07-04 13:40

from django.db import migrations, models

import ludamus.pacts.legacy


def backfill_scheduled_to_accepted(apps, schema_editor):
    Session = apps.get_model("db_main", "Session")
    Session.objects.filter(status="scheduled").update(status="accepted")


class Migration(migrations.Migration):

    dependencies = [("db_main", "0116_merge_20260703_2155")]

    operations = [
        migrations.RunPython(backfill_scheduled_to_accepted, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("accepted", "ACCEPTED"),
                    ("on_hold", "ON_HOLD"),
                    ("rejected", "REJECTED"),
                ],
                default=ludamus.pacts.legacy.SessionStatus["PENDING"],
                max_length=15,
            ),
        ),
    ]
