# Generated by Django 6.0.6 on 2026-07-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0117_migrate_needs_requirements_to_fields")]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag", name="unique_tag_name_per_category"
        ),
        migrations.RemoveField(model_name="session", name="tags"),
        migrations.RemoveField(model_name="event", name="filterable_tag_categories"),
        migrations.RemoveField(model_name="proposalcategory", name="tag_categories"),
        migrations.RemoveConstraint(
            model_name="personaldatafieldvalue",
            name="unique_personal_data_per_user_event_field",
        ),
        migrations.RemoveConstraint(
            model_name="personaldatafieldvalue", name="personal_data_requires_owner"
        ),
        migrations.RemoveField(model_name="session", name="needs"),
        migrations.RemoveField(model_name="session", name="requirements"),
        migrations.RemoveField(model_name="personaldatafieldvalue", name="user"),
        migrations.DeleteModel(name="Tag"),
        migrations.DeleteModel(name="TagCategory"),
    ]
