# Generated by Django 6.0.6 on 2026-07-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0118_backfill_scheduled_sessions_to_accepted")]

    operations = [
        migrations.RemoveConstraint(
            model_name="session", name="session_unique_slug_in_event"
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("slug", "event"),
                name="session_unique_slug_in_event",
            ),
        ),
    ]
