# Generated by Django 6.0.6 on 2026-07-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0119_event_printables_last_printed_at_and_more")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="ident",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ident", ""), _negated=True),
                fields=("event", "ident"),
                name="session_unique_ident_in_event",
            ),
        ),
    ]
