# Generated by Django 6.0.6 on 2026-07-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0118_backfill_scheduled_sessions_to_accepted"),
        ("db_main", "0119_alter_personaldatafieldvalue_event"),
    ]

    operations = []
