# Generated by Django 6.0.6 on 2026-07-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0121_eventpanelsettings")]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="internal_comment",
            field=models.TextField(blank=True, default=""),
        )
    ]
