# Generated by Django 6.0.6 on 2026-07-04 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0122_remove_tag_unique_tag_name_per_category_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldatafieldvalue",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_data_field_values",
                to="db_main.event",
            ),
        )
    ]
