# Generated by Django 6.0.7 on 2026-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0124_session_ident_session_session_unique_ident_in_event")
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="invite_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        )
    ]
