# Generated by Django 6.0.7 on 2026-07-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0127_facilitator_internal_comment"),
        (
            "db_main",
            "0129_alter_domainenrollmentconfig_allowed_slots_per_user_and_more",
        ),
    ]

    operations = []
