"""URL patterns for the chronology panel bounded context."""

from django.urls import include, path

from ludamus.gates.web.django.chronology.panel.views import (
    bans,
    cfp,
    discounts,
    event_settings,
    facilitators,
    google_docs_import,
    index,
    integrations,
    personal_data_fields,
    proposals,
    session_fields,
    time_slots,
    timetable,
    tracks,
    venues,
)
from ludamus.gates.web.django.chronology.panel.views import print as print_views

app_name = "panel"  # pylint: disable=invalid-name

_timetable_urlpatterns = [
    path("", timetable.TimetablePageView.as_view(), name="timetable"),
    path(
        "parts/sessions/",
        timetable.TimetableSessionListPartView.as_view(),
        name="timetable-sessions-part",
    ),
    path(
        "parts/browse-pane/",
        timetable.TimetableBrowsePanePartView.as_view(),
        name="timetable-browse-pane-part",
    ),
    path(
        "parts/session/<int:pk>/",
        timetable.TimetableSessionDetailPartView.as_view(),
        name="timetable-session-detail-part",
    ),
    path(
        "parts/grid/",
        timetable.TimetableGridPartView.as_view(),
        name="timetable-grid-part",
    ),
    path(
        "parts/conflicts/",
        timetable.TimetableConflictsPartView.as_view(),
        name="timetable-conflicts-part",
    ),
    path(
        "do/assign/", timetable.TimetableAssignView.as_view(), name="timetable-assign"
    ),
    path(
        "do/unassign/",
        timetable.TimetableUnassignView.as_view(),
        name="timetable-unassign",
    ),
    path(
        "overview/",
        timetable.TimetableOverviewPageView.as_view(),
        name="timetable-overview",
    ),
    path("log/", timetable.TimetableLogPageView.as_view(), name="timetable-log"),
    path(
        "problems/",
        timetable.TimetableProblemsPageView.as_view(),
        name="timetable-problems",
    ),
    path(
        "do/revert/", timetable.TimetableRevertView.as_view(), name="timetable-revert"
    ),
    path(
        "do/confirm/",
        timetable.TimetableConfirmView.as_view(),
        name="timetable-confirm",
    ),
    path(
        "do/confirm-all/",
        timetable.TimetableConfirmAllView.as_view(),
        name="timetable-confirm-all",
    ),
    path(
        "do/confirm-block/",
        timetable.TimetableConfirmBlockView.as_view(),
        name="timetable-confirm-block",
    ),
    path(
        "print/timetable/",
        print_views.TimetablePrintView.as_view(material="timetable"),
        name="timetable-print",
    ),
    path(
        "print/door-cards/",
        print_views.TimetablePrintView.as_view(material="door-cards"),
        name="timetable-print-door-cards",
    ),
]

urlpatterns = [
    path("", index.PanelIndexRedirectView.as_view(), name="index"),
    path("event/<slug:slug>/", index.EventIndexPageView.as_view(), name="event-index"),
    path(
        "event/<slug:slug>/settings/",
        event_settings.EventSettingsPageView.as_view(),
        name="event-settings",
    ),
    path(
        "event/<slug:slug>/settings/proposals/",
        event_settings.EventProposalSettingsPageView.as_view(),
        name="event-proposal-settings",
    ),
    path(
        "event/<slug:slug>/settings/display/",
        event_settings.EventDisplaySettingsPageView.as_view(),
        name="event-display-settings",
    ),
    path(
        "event/<slug:slug>/settings/integrations/",
        event_settings.EventIntegrationSettingsPageView.as_view(),
        name="event-integration-settings",
    ),
    path("event/<slug:slug>/bans/", bans.BansPageView.as_view(), name="bans"),
    path(
        "event/<slug:slug>/bans/<int:pk>/do/delete",
        bans.BanDeleteActionView.as_view(),
        name="ban-delete",
    ),
    path("event/<slug:slug>/venues/", venues.SpacesPageView.as_view(), name="venues"),
    path(
        "event/<slug:slug>/venues/create/",
        venues.SpaceCreatePageView.as_view(),
        name="space-create",
    ),
    path(
        "event/<slug:slug>/venues/<int:parent_pk>/create/",
        venues.SpaceCreatePageView.as_view(),
        name="space-create-child",
    ),
    path(
        "event/<slug:slug>/venues/<int:pk>/edit/",
        venues.SpaceEditPageView.as_view(),
        name="space-edit",
    ),
    path(
        "event/<slug:slug>/venues/<int:pk>/do/delete",
        venues.SpaceDeleteActionView.as_view(),
        name="space-delete",
    ),
    path(
        "event/<slug:slug>/venues/<int:pk>/do/duplicate",
        venues.SpaceDuplicateActionView.as_view(),
        name="space-duplicate",
    ),
    path(
        "event/<slug:slug>/venues/<int:pk>/do/copy",
        venues.SpaceCopyPageView.as_view(),
        name="space-copy",
    ),
    path(
        "event/<slug:slug>/venues/do/reorder",
        venues.SpaceReorderActionView.as_view(),
        name="space-reorder",
    ),
    path(
        "event/<slug:slug>/cfp/time-slots/",
        time_slots.TimeSlotsPageView.as_view(),
        name="time-slots",
    ),
    path(
        "event/<slug:slug>/cfp/time-slots/create/",
        time_slots.TimeSlotCreatePageView.as_view(),
        name="time-slot-create",
    ),
    path(
        "event/<slug:slug>/cfp/time-slots/<int:pk>/edit/",
        time_slots.TimeSlotEditPageView.as_view(),
        name="time-slot-edit",
    ),
    path(
        "event/<slug:slug>/cfp/time-slots/<int:pk>/do/delete",
        time_slots.TimeSlotDeleteActionView.as_view(),
        name="time-slot-delete",
    ),
    path(
        "event/<slug:slug>/proposals/",
        proposals.ProposalsPageView.as_view(),
        name="proposals",
    ),
    path(
        "event/<slug:slug>/proposals/create/",
        proposals.ProposalCreatePageView.as_view(),
        name="proposal-create",
    ),
    path(
        "event/<slug:slug>/proposals/create/fields/",
        proposals.ProposalCreateFieldsComponentView.as_view(),
        name="proposal-create-fields",
    ),
    path(
        "event/<slug:slug>/proposals/log/",
        proposals.ContentLogPageView.as_view(),
        name="content-log",
    ),
    path(
        "event/<slug:slug>/proposals/log/<int:pk>/revert/",
        proposals.ContentLogRevertActionView.as_view(),
        name="content-log-revert",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/",
        proposals.ProposalDetailPageView.as_view(),
        name="proposal-detail",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/edit/",
        proposals.ProposalEditPageView.as_view(),
        name="proposal-edit",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/edit/fields/",
        proposals.ProposalEditFieldsComponentView.as_view(),
        name="proposal-edit-fields",
    ),
    path(
        "event/<slug:slug>/proposals/do/bulk-status",
        proposals.ProposalBulkStatusActionView.as_view(),
        name="proposal-bulk-status",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/do/pending",
        proposals.ProposalPendingActionView.as_view(),
        name="proposal-pending",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/do/accept",
        proposals.ProposalAcceptActionView.as_view(),
        name="proposal-accept",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/do/hold",
        proposals.ProposalHoldActionView.as_view(),
        name="proposal-hold",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/do/reject",
        proposals.ProposalRejectActionView.as_view(),
        name="proposal-reject",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/do/delete",
        proposals.ProposalDeleteActionView.as_view(),
        name="proposal-delete",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/do/restore",
        proposals.ProposalRestoreActionView.as_view(),
        name="proposal-restore",
    ),
    path(
        "event/<slug:slug>/proposals/<int:proposal_id>/do/set-facilitators",
        proposals.ProposalSetFacilitatorsActionView.as_view(),
        name="proposal-set-facilitators",
    ),
    path("event/<slug:slug>/cfp/", cfp.CFPPageView.as_view(), name="cfp"),
    path(
        "event/<slug:slug>/cfp/create/",
        cfp.CFPCreatePageView.as_view(),
        name="cfp-create",
    ),
    path(
        "event/<slug:slug>/cfp/personal-data/",
        personal_data_fields.PersonalDataFieldsPageView.as_view(),
        name="personal-data-fields",
    ),
    path(
        "event/<slug:slug>/cfp/personal-data/create/",
        personal_data_fields.PersonalDataFieldCreatePageView.as_view(),
        name="personal-data-field-create",
    ),
    path(
        "event/<slug:slug>/cfp/personal-data/<str:field_slug>/edit/",
        personal_data_fields.PersonalDataFieldEditPageView.as_view(),
        name="personal-data-field-edit",
    ),
    path(
        "event/<slug:slug>/cfp/personal-data/<str:field_slug>/do/delete",
        personal_data_fields.PersonalDataFieldDeleteActionView.as_view(),
        name="personal-data-field-delete",
    ),
    path(
        "event/<slug:slug>/cfp/session-fields/",
        session_fields.SessionFieldsPageView.as_view(),
        name="session-fields",
    ),
    path(
        "event/<slug:slug>/cfp/session-fields/create/",
        session_fields.SessionFieldCreatePageView.as_view(),
        name="session-field-create",
    ),
    path(
        "event/<slug:slug>/cfp/session-fields/<str:field_slug>/edit/",
        session_fields.SessionFieldEditPageView.as_view(),
        name="session-field-edit",
    ),
    path(
        "event/<slug:slug>/cfp/session-fields/<str:field_slug>/do/delete",
        session_fields.SessionFieldDeleteActionView.as_view(),
        name="session-field-delete",
    ),
    path(
        "event/<slug:event_slug>/cfp/<str:category_slug>/",
        cfp.CFPEditPageView.as_view(),
        name="cfp-edit",
    ),
    path(
        "event/<slug:event_slug>/cfp/<str:category_slug>/do/delete",
        cfp.CFPDeleteActionView.as_view(),
        name="cfp-delete",
    ),
    path(
        "parts/icon-preview/",
        session_fields.IconPreviewPartView.as_view(),
        name="icon-preview",
    ),
    path("event/<slug:slug>/tracks/", tracks.TracksPageView.as_view(), name="tracks"),
    path(
        "event/<slug:slug>/tracks/create/",
        tracks.TrackCreatePageView.as_view(),
        name="track-create",
    ),
    path(
        "event/<slug:slug>/tracks/<str:track_slug>/edit/",
        tracks.TrackEditPageView.as_view(),
        name="track-edit",
    ),
    path(
        "event/<slug:slug>/tracks/<str:track_slug>/do/delete",
        tracks.TrackDeleteActionView.as_view(),
        name="track-delete",
    ),
    path(
        "event/<slug:slug>/facilitators/",
        facilitators.FacilitatorsPageView.as_view(),
        name="facilitators",
    ),
    path(
        "event/<slug:slug>/facilitators/create/",
        facilitators.FacilitatorCreatePageView.as_view(),
        name="facilitator-create",
    ),
    path(
        "event/<slug:slug>/facilitators/columns/",
        facilitators.FacilitatorColumnsPageView.as_view(),
        name="facilitator-columns",
    ),
    path(
        "event/<slug:slug>/facilitators/merge/",
        facilitators.FacilitatorMergePageView.as_view(),
        name="facilitator-merge",
    ),
    path(
        "event/<slug:slug>/facilitators/<str:facilitator_slug>/",
        facilitators.FacilitatorDetailPageView.as_view(),
        name="facilitator-detail",
    ),
    path(
        "event/<slug:slug>/facilitators/<str:facilitator_slug>/edit/",
        facilitators.FacilitatorEditPageView.as_view(),
        name="facilitator-edit",
    ),
    path(
        "event/<slug:slug>/facilitators/<str:facilitator_slug>/do/flag",
        facilitators.FacilitatorFlagActionView.as_view(),
        name="facilitator-flag",
    ),
    path(
        "event/<slug:slug>/facilitators/<str:facilitator_slug>/do/unflag",
        facilitators.FacilitatorUnflagActionView.as_view(),
        name="facilitator-unflag",
    ),
    path(
        "event/<slug:slug>/facilitators/<str:facilitator_slug>/do/mark-guest",
        facilitators.FacilitatorMarkGuestActionView.as_view(),
        name="facilitator-mark-guest",
    ),
    path(
        "event/<slug:slug>/facilitators/<str:facilitator_slug>/do/assign-organizer",
        facilitators.FacilitatorAssignOrganizerActionView.as_view(),
        name="facilitator-assign-organizer",
    ),
    path(
        "event/<slug:slug>/facilitators/<str:facilitator_slug>/do/unassign-organizer",
        facilitators.FacilitatorUnassignOrganizerActionView.as_view(),
        name="facilitator-unassign-organizer",
    ),
    path(
        "event/<slug:slug>/discounts/",
        discounts.DiscountsPageView.as_view(),
        name="discounts",
    ),
    path(
        "event/<slug:slug>/discounts/export/",
        discounts.DiscountExportPageView.as_view(),
        name="discount-export",
    ),
    path(
        "event/<slug:slug>/discounts/<int:facilitator_id>/assign/",
        discounts.DiscountCreatePageView.as_view(),
        name="discount-assign",
    ),
    path(
        "event/<slug:slug>/discounts/<int:pk>/edit/",
        discounts.DiscountEditPageView.as_view(),
        name="discount-edit",
    ),
    path(
        "event/<slug:slug>/discounts/<int:pk>/do/delete",
        discounts.DiscountDeleteActionView.as_view(),
        name="discount-delete",
    ),
    path("event/<slug:slug>/timetable/", include(_timetable_urlpatterns)),
    path(
        "event/<slug:slug>/print/",
        print_views.PrintMaterialsPageView.as_view(),
        name="print-materials",
    ),
    path(
        "event/<slug:slug>/settings/integrations/check/",
        integrations.IntegrationCheckActionView.as_view(),
        name="integration-check",
    ),
    path(
        "event/<slug:slug>/settings/integrations/add/",
        integrations.IntegrationCreatePageView.as_view(),
        name="integration-create",
    ),
    path(
        "event/<slug:slug>/settings/integrations/<int:pk>/edit/",
        integrations.IntegrationEditPageView.as_view(),
        name="integration-edit",
    ),
    path(
        "event/<slug:slug>/settings/integrations/<int:pk>/delete/",
        integrations.IntegrationDeletePageView.as_view(),
        name="integration-delete",
    ),
    path(
        "event/<slug:slug>/import/",
        google_docs_import.EventImportProposalView.as_view(),
        name="import",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/",
        google_docs_import.EventImportProposalView.as_view(),
        name="import-integration",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/review/",
        google_docs_import.EventImportReviewView.as_view(),
        name="import-review",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/do/save-row/",
        google_docs_import.EventImportRowSaveView.as_view(),
        name="import-row-save",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/do/refetch/",
        google_docs_import.EventImportRefetchView.as_view(),
        name="import-refetch",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/do/import-missing-fields/",
        google_docs_import.EventImportMissingFieldsView.as_view(),
        name="import-missing-fields",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/do/apply-field-layout/",
        google_docs_import.EventImportApplyFieldLayoutView.as_view(),
        name="import-apply-field-layout",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/json/",
        google_docs_import.EventImportJsonView.as_view(),
        name="import-json",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/run/",
        google_docs_import.EventImportRunPageView.as_view(),
        name="import-run",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/do/run/",
        google_docs_import.EventImportRunActionView.as_view(),
        name="import-run-do",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/do/test/",
        google_docs_import.EventImportTestRowActionView.as_view(),
        name="import-test-do",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/log/",
        google_docs_import.EventImportLogPageView.as_view(),
        name="import-log",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/settings/",
        google_docs_import.EventImportSettingsSaveView.as_view(),
        name="import-settings-save",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/do/retry-entry/",
        google_docs_import.EventImportLogRetryActionView.as_view(),
        name="import-log-retry",
    ),
    path(
        "event/<slug:slug>/import/<int:pk>/do/reimport-entry/",
        google_docs_import.EventImportLogReimportActionView.as_view(),
        name="import-log-reimport",
    ),
]
