# Generated by Django 5.2.3 on 2025-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0002_default_site")]

    operations = [
        migrations.AddField(
            model_name="tagcategory",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Bootstrap icon name (e.g., 'tag', 'star', 'heart')",
                max_length=50,
            ),
        )
    ]
