# Generated by Django 5.2.3 on 2025-06-15 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0003_tagcategory_icon")]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
