# Generated by Django 5.2.3 on 2025-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0004_alter_proposal_host")]

    operations = [
        migrations.RemoveConstraint(model_name="session", name="session_date_times"),
        migrations.RemoveField(model_name="session", name="publication_time"),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_time__isnull", True),
                    ("end_time__isnull", True),
                    ("start_time__lt", models.F("end_time")),
                    _connector="OR",
                ),
                name="session_date_times",
            ),
        ),
    ]
