# Generated by Django 5.2.3 on 2025-06-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0006_remove_session_session_date_times_and_more")]

    operations = [
        migrations.AlterField(
            model_name="agendaitem", name="end_time", field=models.DateTimeField()
        ),
        migrations.AlterField(
            model_name="agendaitem", name="start_time", field=models.DateTimeField()
        ),
    ]
