# Generated by Django 5.2.3 on 2025-07-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0008_add_flatpages")]

    operations = [
        migrations.RenameField(
            model_name="proposal", old_name="proposal_category", new_name="category"
        )
    ]
