# Generated by Django 5.2.3 on 2025-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0009_rename_proposal_category_proposal_category")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="presenter_name",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
