# Generated by Django 5.2.3 on 2025-08-03 20:15

from django.db import migrations


def set_leader_name(apps, schema_editor):
    Session = apps.get_model("db_main", "Session")
    for session in Session.objects.all():
        session.presenter_name = session.host.name
        session.save()


class Migration(migrations.Migration):

    dependencies = [("db_main", "0010_session_presenter_name")]

    operations = [migrations.RunPython(set_leader_name)]
