# Generated by Django 5.2.4 on 2025-08-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0011_set_presenter_name")]

    operations = [migrations.RemoveField(model_name="session", name="host")]
