# Generated by Django 5.2.4 on 2025-08-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0012_remove_session_host")]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="presenter_name",
            field=models.CharField(max_length=255),
        )
    ]
