# Generated by Django 5.2.5 on 2025-08-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0013_alter_session_presenter_name")]

    operations = [
        migrations.RemoveField(model_name="event", name="enrollment_end_time"),
        migrations.RemoveField(model_name="event", name="enrollment_start_time"),
        migrations.CreateModel(
            name="EnrollmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "percentage_slots",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Percentage of total session slots available for enrollment (1-100)",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_configs",
                        to="db_main.event",
                    ),
                ),
            ],
            options={
                "db_table": "enrollment_config",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_time__lt", models.F("end_time"))),
                        name="enrollment_config_date_times",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("percentage_slots__gte", 1), ("percentage_slots__lte", 100)
                        ),
                        name="enrollment_config_percentage_range",
                    ),
                ],
            },
        ),
    ]
