# Generated by Django 5.2.5 on 2025-08-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0014_remove_event_enrollment_end_time_and_more")]

    operations = [
        migrations.AddField(
            model_name="enrollmentconfig",
            name="limit_to_end_time",
            field=models.BooleanField(
                default=False,
                help_text="Only allow enrollment for sessions starting before this config's end time",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="min_age",
            field=models.PositiveIntegerField(
                default=0, help_text="Minimum age requirement (0 = no restriction)"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="min_age",
            field=models.PositiveIntegerField(
                default=0, help_text="Minimum age requirement (0 = no restriction)"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_age__gte", 0), ("min_age__lte", 18)),
                name="session_min_age_range",
            ),
        ),
    ]
