# Generated by Django 5.2.5 on 2025-08-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0015_enrollmentconfig_limit_to_end_time_proposal_min_age_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="filterable_tag_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tag categories that will appear as filters in the session list",
                to="db_main.tagcategory",
            ),
        )
    ]
