# Generated by Django 5.2.5 on 2025-08-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0016_event_filterable_tag_categories")]

    operations = [
        migrations.AddField(
            model_name="enrollmentconfig",
            name="banner_text",
            field=models.TextField(
                blank=True, help_text="Banner text to display for active enrollments"
            ),
        ),
        migrations.AddField(
            model_name="enrollmentconfig",
            name="max_waitlist_sessions",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of sessions a user can join waitlist for (0 = waitlist disabled)",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentconfig",
            name="restrict_to_configured_users",
            field=models.BooleanField(
                default=False,
                help_text="Only allow users with explicit UserEnrollmentConfig entries to enroll",
            ),
        ),
        migrations.CreateModel(
            name="DomainEnrollmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Domain name (e.g. 'company.com', 'university.edu')",
                        max_length=255,
                    ),
                ),
                (
                    "allowed_slots_per_user",
                    models.PositiveIntegerField(
                        help_text="Default number of slots per user from this domain"
                    ),
                ),
                (
                    "enrollment_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_configs",
                        to="db_main.enrollmentconfig",
                    ),
                ),
            ],
            options={
                "db_table": "domain_enrollment_config",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment_config", "domain"),
                        name="unique_domain_enrollment_config",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserEnrollmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email address of the user this configuration applies to",
                        max_length=254,
                    ),
                ),
                (
                    "allowed_slots",
                    models.PositiveIntegerField(
                        help_text="Number of slots this user + their connected users can take"
                    ),
                ),
                (
                    "fetched_from_api",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this config was fetched from external API",
                    ),
                ),
                (
                    "enrollment_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_configs",
                        to="db_main.enrollmentconfig",
                    ),
                ),
            ],
            options={
                "db_table": "user_enrollment_config",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment_config", "user_email"),
                        name="unique_user_enrollment_config",
                    )
                ],
            },
        ),
    ]
