# Generated by Django 5.2.5 on 2025-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0017_enrollmentconfig_banner_text_and_more")]

    operations = [
        migrations.AddField(
            model_name="userenrollmentconfig",
            name="last_check",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the membership was checked via API",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domainenrollmentconfig",
            name="allowed_slots_per_user",
            field=models.PositiveIntegerField(
                help_text="Default number of users (including connected users) that can be enrolled by accounts from this domain"
            ),
        ),
        migrations.AlterField(
            model_name="userenrollmentconfig",
            name="allowed_slots",
            field=models.PositiveIntegerField(
                help_text="Maximum number of users (including connected users) that can be enrolled by this account"
            ),
        ),
    ]
