# Generated by Django 5.2.5 on 2025-09-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0018_userenrollmentconfig_last_check_and_more")]

    operations = [
        migrations.AddField(
            model_name="enrollmentconfig",
            name="allow_anonymous_enrollment",
            field=models.BooleanField(
                default=False,
                help_text="Allow anonymous users to enroll without creating accounts",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("connected", "Connected"),
                    ("anonymous", "Anonymous"),
                ],
                default="active",
                max_length=255,
            ),
        ),
    ]
