# Generated by Django 5.2.6 on 2025-10-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0019_enrollmentconfig_allow_anonymous_enrollment_and_more")
    ]

    operations = [migrations.RemoveField(model_name="user", name="birth_date")]
