# Generated by Django 5.2.6 on 2025-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0020_remove_user_birth_date")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_username",
            field=models.CharField(
                blank=True,
                help_text="Your Discord username for session coordination",
                max_length=150,
                verbose_name="Discord username",
            ),
        )
    ]
