# Generated by Django 5.2.6 on 2025-09-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0021_user_discord_username")]

    operations = [migrations.RemoveField(model_name="session", name="guild")]
