# Generated by Django 5.2.6 on 2025-09-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0022_remove_session_guild")]

    operations = [
        migrations.RemoveField(model_name="guild", name="members"),
        migrations.DeleteModel(name="GuildMember"),
    ]
