# Generated by Django 5.2.6 on 2025-09-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0023_remove_guild_members_delete_guildmember")]

    operations = [migrations.DeleteModel(name="Guild")]
