# Generated by Django 6.0 on 2026-01-11 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0025_alter_user_user_type")]

    operations = [
        migrations.CreateModel(
            name="PersonalDataField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_data_fields",
                        to="db_main.event",
                    ),
                ),
            ],
            options={"db_table": "personal_data_field", "ordering": ["order", "name"]},
        ),
        migrations.CreateModel(
            name="HostPersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_personal_data",
                        to="db_main.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="db_main.personaldatafield",
                    ),
                ),
            ],
            options={"db_table": "host_personal_data"},
        ),
        migrations.CreateModel(
            name="PersonalDataFieldRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_data_requirements",
                        to="db_main.proposalcategory",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_requirements",
                        to="db_main.personaldatafield",
                    ),
                ),
            ],
            options={"db_table": "personal_data_field_requirement"},
        ),
        migrations.AddConstraint(
            model_name="personaldatafield",
            constraint=models.UniqueConstraint(
                fields=("event", "slug"),
                name="personal_data_field_unique_slug_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostpersonaldata",
            constraint=models.UniqueConstraint(
                fields=("user", "event", "field"),
                name="unique_personal_data_per_user_event_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="personaldatafieldrequirement",
            constraint=models.UniqueConstraint(
                fields=("category", "field"), name="unique_field_per_category"
            ),
        ),
    ]
