# Generated by Django 6.0 on 2026-01-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0026_add_personal_data_models")]

    operations = [
        migrations.AddField(
            model_name="personaldatafield",
            name="field_type",
            field=models.CharField(
                choices=[("text", "Text"), ("select", "Select")],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PersonalDataFieldOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="db_main.personaldatafield",
                    ),
                ),
            ],
            options={
                "db_table": "personal_data_field_option",
                "ordering": ["order", "label"],
            },
        ),
    ]
