# Generated by Django 6.0 on 2026-01-12 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0028_add_category_durations")]

    operations = [
        migrations.CreateModel(
            name="SessionField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                (
                    "field_type",
                    models.CharField(
                        choices=[("text", "Text"), ("select", "Select")],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_fields",
                        to="db_main.event",
                    ),
                ),
            ],
            options={"db_table": "session_field", "ordering": ["order", "name"]},
        ),
        migrations.CreateModel(
            name="SessionFieldOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="db_main.sessionfield",
                    ),
                ),
            ],
            options={
                "db_table": "session_field_option",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="SessionFieldRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_field_requirements",
                        to="db_main.proposalcategory",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_requirements",
                        to="db_main.sessionfield",
                    ),
                ),
            ],
            options={"db_table": "session_field_requirement"},
        ),
        migrations.AddConstraint(
            model_name="sessionfield",
            constraint=models.UniqueConstraint(
                fields=("event", "slug"), name="session_field_unique_slug_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionfieldrequirement",
            constraint=models.UniqueConstraint(
                fields=("category", "field"), name="unique_session_field_per_category"
            ),
        ),
    ]
