# Generated by Django 6.0 on 2026-01-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0029_add_session_field_models")]

    operations = [
        migrations.AddField(
            model_name="personaldatafieldrequirement",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessionfieldrequirement",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
