# Generated by Django 6.0.1 on 2026-01-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0030_add_order_to_field_requirements")]

    operations = [
        migrations.AddField(
            model_name="personaldatafield",
            name="is_multiple",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionfield",
            name="is_multiple",
            field=models.BooleanField(default=False),
        ),
    ]
