# Generated by Django 6.0.1 on 2026-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0031_add_is_multiple_to_fields")]

    operations = [
        migrations.AddField(
            model_name="personaldatafield",
            name="allow_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionfield",
            name="allow_custom",
            field=models.BooleanField(default=False),
        ),
    ]
