# Generated by Django 6.0.1 on 2026-01-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0032_add_allow_custom_to_fields")]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("address", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="db_main.event",
                    ),
                ),
            ],
            options={
                "db_table": "venue",
                "ordering": ["order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "event"), name="venue_has_unique_slug_and_event"
                    )
                ],
            },
        )
    ]
