# Generated by Django 6.0.1 on 2026-01-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0033_add_venue_model")]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "area", "ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="space", options={"ordering": ["order", "name"]}
        ),
        migrations.RemoveConstraint(
            model_name="space", name="space_has_unique_slug_and_event"
        ),
        migrations.AddField(
            model_name="space",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="space",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="area",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="db_main.event",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="db_main.venue",
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaces",
                to="db_main.area",
            ),
        ),
        migrations.AddConstraint(
            model_name="space",
            constraint=models.UniqueConstraint(
                condition=models.Q(("area__isnull", False)),
                fields=("slug", "area"),
                name="space_has_unique_slug_and_area",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("slug", "venue"), name="area_has_unique_slug_and_venue"
            ),
        ),
    ]
