# Generated by Django 6.0.1 on 2026-01-17 17:49

from django.db import migrations


def migrate_spaces_to_areas(apps, schema_editor):
    """
    Link existing spaces to areas.

    For each event with existing spaces:
    1. Create "Default Venue" if no venues exist
    2. Create "Default Area" for each venue
    3. Link all orphaned spaces to their event's default area
    """
    Event = apps.get_model("db_main", "Event")
    Venue = apps.get_model("db_main", "Venue")
    Area = apps.get_model("db_main", "Area")
    Space = apps.get_model("db_main", "Space")

    # Get all events that have orphaned spaces (spaces without an area)
    events_with_orphaned_spaces = Event.objects.filter(
        spaces__area__isnull=True
    ).distinct()

    for event in events_with_orphaned_spaces:
        # Ensure event has at least one venue
        venue = Venue.objects.filter(event=event).first()
        if venue is None:
            venue = Venue.objects.create(
                event=event,
                name="Default Venue",
                slug="default-venue",
                address="",
                order=0,
            )

        # Ensure venue has at least one area
        area = Area.objects.filter(venue=venue).first()
        if area is None:
            area = Area.objects.create(
                event=event,
                venue=venue,
                name="Default Area",
                slug="default-area",
                description="",
                order=0,
            )

        # Link all orphaned spaces in this event to the default area
        Space.objects.filter(event=event, area__isnull=True).update(area=area)


def reverse_migration(apps, schema_editor):
    """Reverse migration - set area to null for all spaces."""
    Space = apps.get_model("db_main", "Space")
    Space.objects.all().update(area=None)


class Migration(migrations.Migration):

    dependencies = [("db_main", "0034_add_area_model")]

    operations = [migrations.RunPython(migrate_spaces_to_areas, reverse_migration)]
