# Generated by Django 6.0.1 on 2026-01-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0035_migrate_spaces_to_areas")]

    operations = [migrations.RemoveField(model_name="area", name="event")]
