# Generated by Django 6.0.2 on 2026-02-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0036_remove_area_event")]

    operations = [
        migrations.RemoveConstraint(
            model_name="space", name="space_has_unique_slug_and_area"
        ),
        migrations.AlterField(
            model_name="space",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaces",
                to="db_main.area",
            ),
        ),
        migrations.AddConstraint(
            model_name="space",
            constraint=models.UniqueConstraint(
                fields=("slug", "area"), name="space_has_unique_slug_and_area"
            ),
        ),
        migrations.RemoveField(model_name="space", name="event"),
    ]
