# Generated by Django 6.0.1 on 2026-02-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0037_remove_space_event_fk")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Profile avatar URL (e.g. from Auth0)",
                verbose_name="Avatar URL",
            ),
        )
    ]
