# Generated by Django 6.0.2 on 2026-02-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0038_user_avatar_url")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="use_gravatar",
            field=models.BooleanField(
                default=False,
                help_text="Use Gravatar instead of provider avatar",
                verbose_name="Use Gravatar",
            ),
        )
    ]
