# Generated by Django 6.0.2 on 2026-03-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0039_user_use_gravatar")]

    operations = [
        migrations.CreateModel(
            name="TimeSlotRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slot_requirements",
                        to="db_main.proposalcategory",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_requirements",
                        to="db_main.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "time_slot_requirement",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "time_slot"),
                        name="unique_time_slot_per_category",
                    )
                ],
            },
        )
    ]
