# Generated by Django 6.0.2 on 2026-03-01 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0040_timeslotrequirement")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="db_main.proposalcategory",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="needs",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="session",
            name="presenter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presented_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "ACCEPTED"),
                    ("rejected", "REJECTED"),
                    ("scheduled", "SCHEDULED"),
                ],
                default="accepted",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="time_slots",
            field=models.ManyToManyField(blank=True, to="db_main.timeslot"),
        ),
    ]
