# Generated by Django 6.0.2 on 2026-03-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0041_session_expand_for_proposal_merge")]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("accepted", "ACCEPTED"),
                    ("rejected", "REJECTED"),
                    ("scheduled", "SCHEDULED"),
                ],
                default="accepted",
                max_length=15,
            ),
        )
    ]
