# Generated by Django 6.0.3 on 2026-03-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0043_backfill_session_from_proposal")]

    operations = [
        migrations.AlterField(
            model_name="tagcategory",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Heroicon name (e.g., 'puzzle-piece', 'star', 'heart')",
                max_length=50,
            ),
        )
    ]
