# Generated by Django 6.0.3 on 2026-03-07 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ludamus.pacts


class Migration(migrations.Migration):

    dependencies = [("db_main", "0044_alter_tagcategory_icon")]

    operations = [
        migrations.AddField(
            model_name="sphere",
            name="default_page",
            field=models.CharField(
                choices=[("events", "Events"), ("encounters", "Encounters")],
                default=ludamus.pacts.SpherePage["EVENTS"],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sphere",
            name="enabled_pages",
            field=models.JSONField(
                default=ludamus.pacts.SpherePage.all_values,
                help_text="List of enabled page identifiers, e.g. ['events', 'encounters']",
            ),
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("game", models.CharField(blank=True, default="", max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("place", models.CharField(blank=True, default="", max_length=255)),
                ("max_participants", models.PositiveIntegerField(default=0)),
                ("share_code", models.CharField(max_length=6, unique=True)),
                (
                    "header_image",
                    models.ImageField(blank=True, upload_to="encounters/"),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="db_main.sphere",
                    ),
                ),
            ],
            options={"db_table": "encounter"},
        ),
        migrations.CreateModel(
            name="EncounterRSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="db_main.encounter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounter_rsvps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "encounter_rsvp"},
        ),
        migrations.AddConstraint(
            model_name="encounter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_time__isnull", True),
                    ("start_time__lt", models.F("end_time")),
                    _connector="OR",
                ),
                name="encounter_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="encounterrsvp",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    models.Q(("name", ""), _negated=True),
                    _connector="OR",
                ),
                name="encounter_rsvp_user_or_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="encounterrsvp",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("encounter", "user"),
                name="encounter_rsvp_unique_user",
            ),
        ),
    ]
