# Generated by Django 6.0.3 on 2026-03-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0046_remove_anonymous_encounter_rsvp")]

    operations = [
        migrations.AddField(
            model_name="proposalcategory",
            name="description",
            field=models.TextField(blank=True, default=""),
        )
    ]
