# Generated by Django 6.0.3 on 2026-03-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0047_add_description_to_proposal_category")]

    operations = [
        migrations.CreateModel(
            name="SessionFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="db_main.sessionfield",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_values",
                        to="db_main.session",
                    ),
                ),
            ],
            options={
                "db_table": "session_field_value",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "field"),
                        name="unique_session_field_value_per_session",
                    )
                ],
            },
        )
    ]
