# Generated by Django 6.0.3 on 2026-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0048_add_session_field_value_model")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        )
    ]
