# Generated by Django 6.0.3 on 2026-03-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0049_session_contact_email")]

    operations = [
        migrations.CreateModel(
            name="EventProposalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_settings",
                        to="db_main.event",
                    ),
                ),
            ],
            options={"db_table": "event_proposal_settings"},
        )
    ]
