# Generated by Django 6.0.3 on 2026-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0050_eventproposalsettings")]

    operations = [
        migrations.AddField(
            model_name="personaldatafield",
            name="help_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sessionfield",
            name="help_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
