# Generated by Django 6.0.3 on 2026-03-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0052_checkbox_field_type_and_jsonfield_values")]

    operations = [
        migrations.RenameField(
            model_name="session", old_name="presenter_name", new_name="display_name"
        ),
        migrations.AlterField(
            model_name="personaldatafield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sessionfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
