# Generated by Django 6.0.3 on 2026-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0054_add_question_field")]

    operations = [
        migrations.AlterField(
            model_name="proposalcategory",
            name="max_participants_limit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="proposalcategory",
            name="min_participants_limit",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
