# Generated by Django 6.0.3 on 2026-03-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0055_alter_proposalcategory_max_participants_limit_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="personaldatafield",
            name="max_length",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="sessionfield",
            name="max_length",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
