# Generated by Django 6.0.3 on 2026-03-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0056_add_max_length_to_fields")]

    operations = [
        migrations.AddField(
            model_name="personaldatafield",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionfield",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sessionfield",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EventSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="db_main.event",
                    ),
                ),
                (
                    "filterable_session_fields",
                    models.ManyToManyField(blank=True, to="db_main.sessionfield"),
                ),
            ],
            options={"db_table": "event_settings"},
        ),
    ]
