# Generated by Django 6.0.3 on 2026-04-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0057_personaldatafield_is_public_sessionfield_icon_and_more")
    ]

    operations = [migrations.DeleteModel(name="Proposal")]
