# Generated by Django 6.0.3 on 2026-04-07 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0060_rename_filterable_to_displayed")]

    operations = [
        migrations.CreateModel(
            name="Facilitator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Twórca programu",
                "verbose_name_plural": "Twórcy programu",
                "db_table": "facilitator",
            },
        ),
        migrations.RemoveConstraint(
            model_name="hostpersonaldata",
            name="unique_personal_data_per_user_event_field",
        ),
        migrations.AlterField(
            model_name="hostpersonaldata",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facilitator",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilitators",
                to="db_main.event",
            ),
        ),
        migrations.AddField(
            model_name="facilitator",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilitator_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hostpersonaldata",
            name="facilitator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_data",
                to="db_main.facilitator",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="facilitators",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="db_main.facilitator"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="proposed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposed_sessions",
                to="db_main.facilitator",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostpersonaldata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "event", "field"),
                name="unique_personal_data_per_user_event_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostpersonaldata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("facilitator__isnull", False)),
                fields=("facilitator", "event", "field"),
                name="unique_personal_data_per_facilitator_event_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilitator",
            constraint=models.UniqueConstraint(
                fields=("event", "slug"), name="facilitator_unique_slug_per_event"
            ),
        ),
    ]
