# Generated by Django 6.0.3 on 2026-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0062_populate_facilitators")]

    operations = [
        migrations.AddField(
            model_name="eventproposalsettings",
            name="allow_anonymous_proposals",
            field=models.BooleanField(default=False),
        )
    ]
