# Generated by Django 6.0.4 on 2026-04-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0063_eventproposalsettings_allow_anonymous_proposals")]

    operations = [
        migrations.AddConstraint(
            model_name="hostpersonaldata",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    ("facilitator__isnull", False),
                    _connector="OR",
                ),
                name="personal_data_requires_owner",
            ),
        )
    ]
