# Generated by Django 6.0.4 on 2026-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0064_hostpersonaldata_personal_data_requires_owner")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="duration",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 8601 duration, e.g. PT1H30M",
                max_length=20,
            ),
        )
    ]
