# Generated by Django 6.0.4 on 2026-04-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0065_session_duration")]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("is_public", models.BooleanField(default=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="db_main.event",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_tracks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spaces",
                    models.ManyToManyField(
                        blank=True, related_name="tracks", to="db_main.space"
                    ),
                ),
            ],
            options={"db_table": "track", "ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="session",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="db_main.track"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("event", "slug"), name="track_unique_slug_per_event"
            ),
        ),
    ]
