# Generated by Django 6.0.4 on 2026-04-23 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0068_remove_session_proposed_by")]

    operations = [
        migrations.CreateModel(
            name="ScheduleChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assign", "Assign"),
                            ("unassign", "Unassign"),
                            ("revert", "Revert"),
                        ],
                        max_length=16,
                    ),
                ),
                ("old_start_time", models.DateTimeField(blank=True, null=True)),
                ("old_end_time", models.DateTimeField(blank=True, null=True)),
                ("new_start_time", models.DateTimeField(blank=True, null=True)),
                ("new_end_time", models.DateTimeField(blank=True, null=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_change_logs",
                        to="db_main.event",
                    ),
                ),
                (
                    "new_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_schedule_change_logs",
                        to="db_main.space",
                    ),
                ),
                (
                    "old_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_schedule_change_logs",
                        to="db_main.space",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_change_logs",
                        to="db_main.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "schedule_change_log", "ordering": ["-creation_time"]},
        )
    ]
