# Generated by Django 6.0.4 on 2026-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0069_schedulechangelog")]

    operations = [
        migrations.AddIndex(
            model_name="agendaitem",
            index=models.Index(
                fields=["space_id", "start_time", "end_time"],
                name="agenda_item_space_time_idx",
            ),
        )
    ]
