# Generated by Django 6.0.4 on 2026-05-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0071_merge_accepted_into_pending")]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("google", "Google Forms + Sheets")], max_length=32
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="db_main.sphere",
                    ),
                ),
            ],
            options={
                "db_table": "connection",
                "ordering": ("display_name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sphere", "display_name"),
                        name="connection_unique_display_name_per_sphere",
                    )
                ],
            },
        )
    ]
