# Generated by Django 6.0.4 on 2026-05-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0072_connection")]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="credentials",
            field=models.BinaryField(default=b""),
        )
    ]
