# Generated by Django 6.0.4 on 2026-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0073_connection_credentials")]

    operations = [
        migrations.AlterField(
            model_name="hostpersonaldata",
            name="value",
            field=models.JSONField(default=str),
        ),
        migrations.AlterField(
            model_name="sessionfieldvalue",
            name="value",
            field=models.JSONField(default=str),
        ),
    ]
