# Generated by Django 6.0.4 on 2026-05-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0074_alter_hostpersonaldata_value_and_more")]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="last_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="last_check_detail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="connection",
            name="last_check_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Not checked yet"),
                    ("ok", "OK"),
                    ("auth_failed", "Authentication failed"),
                    ("network_error", "Network error"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
