# Generated by Django 6.0.5 on 2026-05-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0076_simplify_connection")]

    operations = [
        migrations.CreateModel(
            name="EventIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("implementation", models.CharField(max_length=128)),
                ("display_name", models.CharField(max_length=255)),
                ("config_json", models.JSONField(default=dict)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_integrations",
                        to="db_main.connection",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="db_main.event",
                    ),
                ),
            ],
            options={
                "db_table": "event_integration",
                "ordering": ("kind", "display_name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "kind", "display_name"),
                        name="event_integration_unique_display_name",
                    )
                ],
            },
        )
    ]
