# Generated by Django 6.0.5 on 2026-05-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0077_eventintegration")]

    operations = [
        migrations.AlterField(
            model_name="eventintegration",
            name="config_json",
            field=models.TextField(default="{}"),
        )
    ]
