# Generated by Django 6.0.5 on 2026-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0079_remove_session_session_min_age_range_and_more")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_facilitator_session_edit",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sphere",
            name="allow_facilitator_session_edit",
            field=models.BooleanField(default=True),
        ),
    ]
