# Generated by Django 6.0.5 on 2026-05-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0079_remove_session_session_min_age_range_and_more")]

    operations = [
        migrations.AddField(
            model_name="eventintegration",
            name="settings_json",
            field=models.TextField(default="{}"),
        )
    ]
