# Generated by Django 6.0.5 on 2026-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0080_event_allow_facilitator_session_edit_and_more")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="logo",
            field=models.ImageField(blank=True, upload_to="events/"),
        )
    ]
