# Generated by Django 6.0.3 on 2026-04-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0080_event_allow_facilitator_session_edit_and_more")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="events/"),
        ),
        migrations.AddField(
            model_name="session",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="sessions/"),
        ),
    ]
