# Generated by Django 6.0.5 on 2026-06-04 14:45

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ludamus.pacts.legacy


class Migration(migrations.Migration):

    dependencies = [("db_main", "0082_contentchangelog")]

    operations = [
        migrations.AddField(
            model_name="proposalcategory",
            name="offer_claim_window",
            field=models.DurationField(
                default=datetime.timedelta(days=1),
                help_text="How long an offered seat is held before it rolls to the next waiter",
            ),
        ),
        migrations.AddField(
            model_name="proposalcategory",
            name="promotion_mode",
            field=models.CharField(
                choices=[("auto", "AUTO"), ("offer_claim", "OFFER_CLAIM")],
                default=ludamus.pacts.legacy.PromotionMode["AUTO"],
                help_text="How a freed seat is filled: AUTO promotes the next waiter straight to confirmed; OFFER_CLAIM offers the seat for a bounded window.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipation",
            name="claim_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipation",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionparticipation",
            name="offer_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionparticipation",
            name="offered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessionparticipation",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "CONFIRMED"),
                    ("waiting", "WAITING"),
                    ("offered", "OFFERED"),
                ],
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("waitlist_promoted", "WAITLIST_PROMOTED"),
                            ("waitlist_offer", "WAITLIST_OFFER"),
                            ("offer_expired", "OFFER_EXPIRED"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, default="")),
                ("url", models.CharField(blank=True, default="", max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-creation_time"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"], name="notif_recipient_read_idx"
                    )
                ],
            },
        ),
    ]
