# Generated by Django 6.0.6 on 2026-06-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0083_proposalcategory_offer_claim_window_and_more"),
        ("db_main", "0085_merge_20260610_1245"),
    ]

    operations = []
