# Generated by Django 6.0.6 on 2026-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0090_merge_logo")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="auto_confirm_sessions",
            field=models.BooleanField(default=True),
        )
    ]
