# Generated by Django 6.0.6 on 2026-06-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0086_merge_20260613_2116"),
        ("db_main", "0091_event_auto_confirm_sessions"),
    ]

    operations = []
