# Generated by Django 6.0.6 on 2026-06-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0092_merge_import_and_main")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        )
    ]
