# Generated by Django 6.0.6 on 2026-06-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0093_session_deleted_at")]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "Percent"), ("amount", "Amount")],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="db_main.event",
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="db_main.facilitator",
                    ),
                ),
            ],
            options={
                "db_table": "discount",
                "ordering": ("-creation_time",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("event", "facilitator"),
                        name="discount_unique_alive_per_event_facilitator",
                    )
                ],
            },
        )
    ]
