# Generated by Django 6.0.6 on 2026-06-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0097_session_event_required")]

    operations = [
        migrations.RemoveConstraint(
            model_name="session", name="session_unique_slug_in_sphere"
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("slug", "event"), name="session_unique_slug_in_event"
            ),
        ),
        migrations.RemoveField(model_name="session", name="sphere"),
    ]
