# Generated by Django 6.0.6 on 2026-06-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0101_space_event_required")]

    operations = [
        migrations.RemoveConstraint(
            model_name="space", name="space_has_unique_slug_and_area"
        ),
        migrations.AddField(
            model_name="space",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="space",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="db_main.space",
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaces",
                to="db_main.area",
            ),
        ),
        migrations.AddConstraint(
            model_name="space",
            constraint=models.UniqueConstraint(
                fields=("slug", "parent"), name="space_has_unique_slug_and_parent"
            ),
        ),
    ]
