# Generated by Django 6.0.6 on 2026-06-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0103_backfill_space_tree")]

    operations = [
        migrations.RemoveConstraint(
            model_name="area", name="area_has_unique_slug_and_venue"
        ),
        migrations.RemoveField(model_name="space", name="area"),
        migrations.RemoveConstraint(
            model_name="venue", name="venue_has_unique_slug_and_event"
        ),
        migrations.RemoveField(model_name="venue", name="event"),
        migrations.DeleteModel(name="Area"),
        migrations.DeleteModel(name="Venue"),
    ]
