# Generated by Django 6.0.6 on 2026-06-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0104_drop_venue_area")]

    operations = [
        migrations.AddConstraint(
            model_name="space",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("event", "slug"),
                name="space_root_has_unique_slug_per_event",
            ),
        )
    ]
