# Generated by Django 6.0.6 on 2026-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0105_space_space_root_has_unique_slug_per_event")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="use_participants_label",
            field=models.BooleanField(default=False),
        )
    ]
