# Generated by Django 6.0.5 on 2026-06-26 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ludamus.pacts.party


class Migration(migrations.Migration):
    dependencies = [("db_main", "0108_user_claim_token")]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_parties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "party"},
        ),
        migrations.CreateModel(
            name="PartyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_mode",
                    models.CharField(
                        choices=[
                            ("accept_by_default", "ACCEPT_BY_DEFAULT"),
                            ("accept_invites", "ACCEPT_INVITES"),
                        ],
                        default=ludamus.pacts.party.PartyConsentMode["ACCEPT_INVITES"],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "ACTIVE"), ("invited", "INVITED")],
                        default=ludamus.pacts.party.PartyMembershipStatus["ACTIVE"],
                        max_length=32,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="db_main.party",
                    ),
                ),
            ],
            options={
                "db_table": "party_membership",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("party", "member"), name="party_membership_unique"
                    )
                ],
            },
        ),
    ]
