# Generated by Django 6.0.6 on 2026-07-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0110_backfill_parties")]

    operations = [migrations.RemoveField(model_name="user", name="manager")]
