# Generated by Django 6.0.6 on 2026-07-02 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0114_alter_notification_kind")]

    operations = [
        migrations.AddField(
            model_name="sessionparticipation",
            name="enrolled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="participants",
            field=models.ManyToManyField(
                through="db_main.SessionParticipation",
                through_fields=("session", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
