# Generated by Django 6.0.6 on 2026-07-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db_main", "0119_event_printables_last_printed_at_and_more")]

    operations = [
        migrations.RenameModel(
            old_name="HostPersonalData", new_name="PersonalDataFieldValue"
        ),
        migrations.AlterModelTable(
            name="personaldatafieldvalue", table="personal_data_field_value"
        ),
    ]
