# Generated by Django 6.0.6 on 2026-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0124_session_ident_session_session_unique_ident_in_event")
    ]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="flagged_for_deletion",
            field=models.BooleanField(default=False),
        )
    ]
