# Generated by Django 6.0.7 on 2026-07-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0128_alter_party_invite_token_unique")]

    operations = [
        migrations.AlterField(
            model_name="domainenrollmentconfig",
            name="allowed_slots_per_user",
            field=models.PositiveIntegerField(
                help_text="Default number of users (including companions) that can be enrolled by accounts from this domain"
            ),
        ),
        migrations.AlterField(
            model_name="userenrollmentconfig",
            name="allowed_slots",
            field=models.PositiveIntegerField(
                help_text="Maximum number of users (including companions) that can be enrolled by this account"
            ),
        ),
    ]
