# Generated by Django 6.0.7 on 2026-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0129_alter_domainenrollmentconfig_allowed_slots_per_user_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        )
    ]
