# Generated by Django 6.0.6 on 2026-07-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0131_facilitator_flagged_for_deletion")]

    operations = [
        migrations.CreateModel(
            name="EventPanelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "displayed_facilitator_fields",
                    models.ManyToManyField(blank=True, to="db_main.personaldatafield"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_settings",
                        to="db_main.event",
                    ),
                ),
            ],
            options={"db_table": "event_panel_settings"},
        )
    ]
