# Generated by Django 6.0.7 on 2026-07-23 16:07

from django.db import migrations, models

import ludamus.links.db.django.models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0134_facilitator_columns")]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="header_image",
            field=models.ImageField(
                blank=True, upload_to=ludamus.links.db.django.models.hashed_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True, upload_to=ludamus.links.db.django.models.hashed_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to=ludamus.links.db.django.models.hashed_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="cover_image",
            field=models.ImageField(
                blank=True, upload_to=ludamus.links.db.django.models.hashed_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="sphere",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to=ludamus.links.db.django.models.hashed_upload_to
            ),
        ),
    ]
