# Generated by Django 6.0.7 on 2026-07-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "db_main",
            "0135_alter_encounter_header_image_alter_event_cover_image_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="eventpanelsettings",
            name="proposal_columns",
            field=models.JSONField(blank=True, default=list),
        )
    ]
