# Generated by Django 6.0.7 on 2026-07-24 13:08

from django.db import migrations, models

import ludamus.links.db.django.uploads


class Migration(migrations.Migration):

    dependencies = [
        (
            "db_main",
            "0135_alter_encounter_header_image_alter_event_cover_image_and_more",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="logo",
            field=models.FileField(
                blank=True, upload_to=ludamus.links.db.django.uploads.unique_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="sphere",
            name="logo",
            field=models.FileField(
                blank=True, upload_to=ludamus.links.db.django.uploads.unique_upload_to
            ),
        ),
    ]
