# Generated by Django 6.0.7 on 2026-07-24 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0137_eventpanelsettings_proposal_columns")]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_facilitators",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
