# Generated by Django 6.0.7 on 2026-08-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0139_facilitator_ident")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="auto_confirm_sessions",
            field=models.BooleanField(default=False),
        )
    ]
