# Generated by Django 6.0.7 on 2026-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0139_purge_blank_field_values")]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="ident",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="facilitator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ident", ""), _negated=True),
                fields=("event", "ident"),
                name="facilitator_unique_ident_per_event",
            ),
        ),
    ]
