# Generated by Django 6.0.7 on 2026-08-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0139_facilitator_ident")]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        )
    ]
