# Generated by Django 6.0.7 on 2026-08-06 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0141_eventpanelsettings_proposal_columns")]

    operations = [
        migrations.AddField(
            model_name="sphere",
            name="parley_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ParleyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=64)),
                ("message_id", models.PositiveBigIntegerField()),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parley_reports",
                        to="db_main.user",
                    ),
                ),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parley_reports",
                        to="db_main.sphere",
                    ),
                ),
            ],
            options={
                "db_table": "parley_report",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reporter", "room_id", "message_id"),
                        name="parley_report_unique_reporter_message",
                    )
                ],
            },
        ),
    ]
