# Generated by Django 6.0.8 on 2026-08-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0142_guild_guildmembership")]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="multi_session",
            field=models.BooleanField(default=False),
        )
    ]
