# Generated by Django 6.0.7 on 2026-08-12 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0143_normalize_durations")]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facilitators",
                to="db_main.guild",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilitator",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("guild__isnull", True), ("user__isnull", True), _connector="OR"
                ),
                name="facilitator_guild_only_when_accountless",
            ),
        ),
    ]
