# Generated by Django 6.0.8 on 2026-08-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0144_facilitator_guild")]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="header_image_original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="cover_image_original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="logo_original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="guild",
            name="logo_original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="session",
            name="cover_image_original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sphere",
            name="logo_original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
