# Generated by Django 6.0.8 on 2026-08-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0145_original_filenames")]

    operations = [
        migrations.AddField(
            model_name="eventintegration",
            name="last_run_json",
            field=models.TextField(default="{}"),
        )
    ]
