# Generated by Django 6.0.8 on 2026-08-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0146_eventintegration_last_run_json")]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="is_collective",
            field=models.BooleanField(default=False),
        )
    ]
