# Generated by Django 6.0.8 on 2026-08-15 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0147_sphere_membership_role")]

    operations = [
        migrations.AddField(
            model_name="schedulechangelog",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_schedule_change_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedulechangelog",
            name="acknowledgement_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
