# Generated by Django 6.0.8 on 2026-08-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0148_alter_facilitator_accreditation_type")]

    operations = [
        migrations.CreateModel(
            name="DiscountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("started_hours", "Started_Hours"),
                            ("session_count", "Session_Count"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_rules",
                        to="db_main.event",
                    ),
                ),
            ],
            options={"db_table": "discount_rule", "ordering": ("order", "pk")},
        )
    ]
