# Generated by Django 6.0.8 on 2026-08-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0142_parley"),
        ("db_main", "0150_track_unique_name_per_event"),
    ]

    operations = []
