# Generated by Django 6.0.8 on 2026-08-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0151_schedulechangelog_important")]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="db_main.event",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="sphere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="db_main.sphere",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["event", "is_published"], name="announcement_event_pub_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sphere__isnull", True), ("event__isnull", True), _connector="XOR"
                ),
                name="announcement_single_scope",
            ),
        ),
    ]
