# Generated by Django 6.1 on 2026-08-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0151_merge_0142_parley_0150_track_unique_name_per_event"),
        ("db_main", "0151_schedulechangelog_important"),
    ]

    operations = []
