# Generated by Django 6.1 on 2026-08-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0151_schedulechangelog_important")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cover_image_preview",
            field=models.CharField(blank=True, default="", max_length=1024),
        )
    ]
