# Generated by Django 6.1 on 2026-08-26 11:03

from django.db import migrations, models

import ludamus.pacts.legacy


class Migration(migrations.Migration):

    dependencies = [("db_main", "0151_schedulechangelog_important")]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sphere",
            name="encounter_public_policy",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("managers", "Managers"),
                    ("everyone", "Everyone"),
                ],
                default=ludamus.pacts.legacy.EncounterPublicPolicy["DISABLED"],
                max_length=20,
            ),
        ),
    ]
