# Generated by Django 6.0.8 on 2026-08-16 07:01

from django.db import migrations, models

import ludamus.pacts.submissions


class Migration(migrations.Migration):

    dependencies = [("db_main", "0151_schedulechangelog_important")]

    operations = [
        migrations.AlterField(
            model_name="facilitator",
            name="accreditation_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("standard", "Standard"),
                    ("guest", "Guest"),
                    ("honorary", "Honorary"),
                    ("creator", "Creator"),
                ],
                default=ludamus.pacts.submissions.AccreditationType["NONE"],
                max_length=20,
            ),
        )
    ]
