# Generated by Django 6.1 on 2026-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0152_encounter_is_public_sphere_encounter_public_policy")
    ]

    operations = [
        migrations.AlterField(
            model_name="sphere",
            name="default_page",
            field=models.CharField(
                choices=[
                    ("events", "Events"),
                    ("encounters", "Encounters"),
                    ("timeline", "Timeline"),
                ],
                default="events",
                max_length=20,
            ),
        )
    ]
