# Generated by Django 6.1 on 2026-08-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0153_alter_sphere_default_page")]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_impromptu",
            field=models.BooleanField(default=False),
        )
    ]
