# Generated by Django 6.0.8 on 2026-08-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0153_alter_sphere_default_page"),
        ("db_main", "0153_discountrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="from_rules",
            field=models.BooleanField(default=False),
        )
    ]
