# Generated by Django 6.1 on 2026-08-28 21:35

from django.db import migrations, models

import ludamus.pacts.legacy


class Migration(migrations.Migration):

    dependencies = [("db_main", "0154_session_is_impromptu")]

    operations = [
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("is_impromptu", True),
                    ("status", ludamus.pacts.legacy.SessionStatus["PENDING"]),
                ),
                fields=("event", "presenter"),
                name="session_one_pending_impromptu_claim_per_presenter",
            ),
        )
    ]
