# Generated by Django 6.1 on 2026-08-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0154_discount_from_rules")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        )
    ]
