# Generated by Django 6.1 on 2026-08-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0154_user_email_verified")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="pending email address",
            ),
        ),
    ]
