# Generated by Django 6.1 on 2026-08-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0152_merge_20260824_1211"),
        ("db_main", "0155_eventintegration_last_run_json"),
    ]

    operations = []
