# Generated by Django 6.1 on 2026-08-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0155_event_address"),
        ("db_main", "0155_eventintegration_last_run_json"),
    ]

    operations = []
