# Generated by Django 6.1 on 2026-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0156_merge_event_address_and_eventintegration")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Profile avatar URL (e.g. from Auth0)",
                max_length=500,
                verbose_name="Avatar URL",
            ),
        )
    ]
