# Generated by Django 6.1 on 2026-09-03 08:35

import django.db.models.deletion
from django.db import migrations, models

import ludamus.links.db.django.uploads


class Migration(migrations.Migration):

    dependencies = [("db_main", "0156_merge_event_address_and_eventintegration")]

    operations = [
        migrations.CreateModel(
            name="EventMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        upload_to=ludamus.links.db.django.uploads.unique_upload_to
                    ),
                ),
                (
                    "image_original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps",
                        to="db_main.event",
                    ),
                ),
                (
                    "spaces",
                    models.ManyToManyField(
                        blank=True, related_name="maps", to="db_main.space"
                    ),
                ),
            ],
            options={"db_table": "event_map", "ordering": ["pk"]},
        )
    ]
