# Generated by Django 6.1 on 2026-08-28 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0156_merge_event_address_and_eventintegration")]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("waitlist_promoted", "WAITLIST_PROMOTED"),
                    ("waitlist_offer", "WAITLIST_OFFER"),
                    ("offer_expired", "OFFER_EXPIRED"),
                    ("shadowbanned_signup", "SHADOWBANNED_SIGNUP"),
                    ("party_invite", "PARTY_INVITE"),
                    ("party_enrolled", "PARTY_ENROLLED"),
                    ("party_seat_held", "PARTY_SEAT_HELD"),
                    ("printables_ready", "PRINTABLES_READY"),
                    ("announcement", "ANNOUNCEMENT"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("muted", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(choices=[("visit", "VISIT")], max_length=16),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to="db_main.sphere",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_subscription",
                "indexes": [
                    models.Index(
                        fields=["sphere", "muted"], name="notifsub_sphere_muted_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "sphere"), name="notifsub_unique_user_sphere"
                    )
                ],
            },
        ),
    ]
