# Generated by Django 6.1 on 2026-09-01 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0156_merge_event_address_and_eventintegration")]

    operations = [
        migrations.CreateModel(
            name="CofacilitatorResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fragment", models.CharField(max_length=255)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cofacilitator_resolutions",
                        to="db_main.sessionfield",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cofacilitator_resolutions",
                        to="db_main.session",
                    ),
                ),
            ],
            options={
                "db_table": "cofacilitator_resolution",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "field", "fragment"),
                        name="unique_cofacilitator_resolution",
                    )
                ],
            },
        )
    ]
