# Generated by Django 6.1 on 2026-09-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0157_alter_user_avatar_url"),
        ("db_main", "0157_eventmap"),
    ]

    operations = []
