# Generated by Django 6.1 on 2026-09-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0156_merge_event_address_and_eventintegration"),
        ("db_main", "0157_session_session_one_pending_impromptu_claim_per_presenter"),
    ]

    operations = []
