# Generated by Django 6.1 on 2026-09-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0159_alter_notification_kind"),
        ("db_main", "0160_eventmappage"),
    ]

    operations = []
