# Generated by Django 6.1 on 2026-09-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0158_cofacilitatorresolution"),
        ("db_main", "0160_eventmappage"),
    ]

    operations = []
