# Generated by Django 6.1 on 2026-09-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0156_merge_20260830_1234"),
        ("db_main", "0160_eventmappage"),
    ]

    operations = []
