# Generated by Django 6.1 on 2026-09-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0161_merge_impromptu_and_maps"),
        ("db_main", "0161_space_programme_order"),
    ]

    operations = []
