# Generated by Django 6.1 on 2026-09-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0161_merge_0156_merge_20260830_1234_0160_eventmappage"),
        ("db_main", "0161_space_programme_order"),
    ]

    operations = []
