# Generated by Django 6.1 on 2026-09-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0159_stamp_announcements_notified"),
        ("db_main", "0161_space_programme_order"),
    ]

    operations = []
