# Generated by Django 6.1 on 2026-09-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0161_remove_encounterrsvp_ip_address"),
        ("db_main", "0162_rename_session_facilitator_name"),
    ]

    operations = []
