# Generated by Django 6.1 on 2026-09-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0162_merge_20260909_1224"),
        ("db_main", "0162_rename_session_facilitator_name"),
    ]

    operations = []
