# Generated by Django 6.1.1 on 2026-09-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0161_remove_encounterrsvp_ip_address"),
        ("db_main", "0163_encounters_policy"),
    ]

    operations = []
