# Generated by Django 6.1.1 on 2026-09-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0163_encounters_policy"),
        ("db_main", "0163_merge_20260912_1207"),
    ]

    operations = []
