# Generated by Django 6.1 on 2026-09-15 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def mark_existing_events_announced(apps, schema_editor):
    """Stamp every already-published event so the sweep never announces it.

    Subscriptions start empty, but an event published long before this
    migration must not become "new" the moment someone subscribes.
    """
    del schema_editor
    event_model = apps.get_model("db_main", "Event")
    event_model.objects.filter(publication_time__isnull=False).update(
        subscribers_announced_at=F("publication_time")
    )


def unmark_events(apps, schema_editor):
    del schema_editor
    apps.get_model("db_main", "Event").objects.update(subscribers_announced_at=None)


class Migration(migrations.Migration):

    dependencies = [("db_main", "0163_encounters_policy")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="subscribers_announced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_events_announced, unmark_events),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("waitlist_promoted", "WAITLIST_PROMOTED"),
                    ("waitlist_offer", "WAITLIST_OFFER"),
                    ("offer_expired", "OFFER_EXPIRED"),
                    ("shadowbanned_signup", "SHADOWBANNED_SIGNUP"),
                    ("party_invite", "PARTY_INVITE"),
                    ("party_enrolled", "PARTY_ENROLLED"),
                    ("party_seat_held", "PARTY_SEAT_HELD"),
                    ("printables_ready", "PRINTABLES_READY"),
                    ("sphere_event_published", "SPHERE_EVENT_PUBLISHED"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SphereSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="db_main.sphere",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sphere_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sphere_subscription",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sphere", "user"),
                        name="sphere_subscription_unique_user",
                    )
                ],
            },
        ),
    ]
