# Generated by Django 6.1.1 on 2026-09-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0164_merge_20260921_1212"),
        ("db_main", "0165_sphere_subscriptions"),
    ]

    operations = []
