# Generated by Django 6.1.1 on 2026-09-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0164_merge_0163_encounters_policy_0163_merge_20260912_1207"),
        ("db_main", "0165_sphere_subscriptions"),
    ]

    operations = []
