# Generated by Django 6.1.1 on 2026-09-30 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _fill_missing_ip(apps, schema_editor):
    # NOTE: calendar-reply signups carry no address; the old NOT NULL column
    # needs one, so they get the RFC 5737 documentation address.
    apps.get_model("db_main", "EncounterRSVP").objects.filter(
        ip_address__isnull=True
    ).update(ip_address="192.0.2.0")


class Migration(migrations.Migration):

    dependencies = [("db_main", "0166_sphere_visibility")]

    operations = [
        migrations.AlterField(
            model_name="encounterrsvp",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, _fill_missing_ip),
        migrations.CreateModel(
            name="EncounterInvitee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("removed", "Removed"),
                        ],
                        default="invited",
                        max_length=8,
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_encounter_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitees",
                        to="db_main.encounter",
                    ),
                ),
            ],
            options={
                "db_table": "encounter_invitee",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("encounter", "email"),
                        name="encounter_invitee_unique_email",
                    )
                ],
            },
        ),
    ]
