# Generated by Django 6.0.8 on 2026-10-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0166_merge_email_verification_and_programme_order")]

    operations = [
        migrations.AlterField(
            model_name="personaldatafield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("discord", "Discord username"),
                ],
                default="text",
                max_length=20,
            ),
        )
    ]
