# Generated by Django 6.1.1 on 2026-09-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0164_merge_20260921_1212"),
        ("db_main", "0166_sphere_visibility"),
    ]

    operations = []
