# Generated by Django 6.1.1 on 2026-09-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0163_session_schedule_confirmed"),
        ("db_main", "0169_encounter_invite_mailing"),
    ]

    operations = []
