# Generated by Django 6.1.1 on 2026-09-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0166_merge_20260924_1220"),
        ("db_main", "0166_sphere_visibility"),
    ]

    operations = []
