# Generated by Django 6.1.1 on 2026-09-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0163_personal_data_field_is_required"),
        ("db_main", "0166_sphere_visibility"),
    ]

    operations = []
