# Generated by Django 6.1.1 on 2026-10-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0167_encounter_invitee"),
        ("db_main", "0167_personaldatafield_discord_type"),
    ]

    operations = []
