# Generated by Django 6.1.1 on 2026-10-01 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0168_merge_encounter_invitee_discord_type")]

    operations = [
        migrations.CreateModel(
            name="EncounterInviteMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounter_invite_mailings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "encounter_invite_mailing",
                "indexes": [
                    models.Index(
                        fields=["creator", "creation_time"],
                        name="encounter_mailing_by_creator",
                    )
                ],
            },
        )
    ]
