# Generated by Django 6.1.1 on 2026-10-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_main", "0172_session_schedule_confirmed"),
        ("db_main", "0174_alter_notification_kind"),
    ]

    operations = []
