# Generated by Django 6.1 on 2026-08-28 08:29

from django.db import migrations, models


def _grandfather_existing_addresses(apps, schema_editor):
    # Pre-verification accounts have been receiving our mail at this address
    # all along; treating them as unverified would silence delivery for the
    # whole platform the day this lands.
    del schema_editor
    user_model = apps.get_model("db_main", "User")
    user_model.objects.exclude(email="").update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [("db_main", "0175_merge_schedule_confirmed_and_notification_kind")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="The user proved control of this address.",
                verbose_name="email verified",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="pending email address",
            ),
        ),
        migrations.RunPython(
            _grandfather_existing_addresses, migrations.RunPython.noop
        ),
    ]
