name: Deploy to production

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy-coolify.yml
    with:
      environment: production-coolify
      environment_url: https://zagrajmy.net
      sha: ${{ github.sha }}
    secrets: inherit
